esphome:
  name: waveshare-dashboard
  friendly_name: Waveshare Dashboard

  on_boot:
    priority: 600
    then:
      - logger.log: "Start panelu Waveshare Dashboard"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  level: INFO
  baud_rate: 115200

api:
  encryption:
    key: "WPISZ_TUTAJ_SWOJ_KLUCZ_API"

ota:
  - platform: esphome
    password: "WPISZ_TUTAJ_SWOJE_HASLO_OTA"

wifi:
  ssid: "ESPTest"
  password: "12345678"

  ap:
    ssid: "Waveshare Dashboard Hotspot"
    password: "12345678"

captive_portal:

web_server:
  port: 80

time:
  - platform: homeassistant
    id: ha_time

sensor:
  - platform: wifi_signal
    name: "Siła WiFi"
    update_interval: 60s

  - platform: uptime
    name: "Czas pracy panelu"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Adres IP panelu"

globals:
  - id: current_page
    type: int
    restore_value: no
    initial_value: "0"
