name: Kompilacja ESPHome

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Instalacja ESPHome
        run: |
          python -m pip install --upgrade pip
          pip install esphome

      - name: Kompilacja pliku konfiguracyjnego
        run: esphome compile Pogoda.yaml

      - name: Udostępnienie pliku BIN
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .esphome/build/waveshare-dashboard/.pioenvs/waveshare-dashboard/firmware.bin
