name: Kompilacja ESPHome

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Instalacja ESPHome
        run: |
          python -m pip install --upgrade pip
          pip install esphome

      - name: Kompilacja
        run: esphome compile Pogoda.yaml

      - name: Znajdź firmware.bin
        run: |
          echo "Szukam firmware.bin..."
          find . -type f -name "firmware.bin"
          FILE=$(find . -type f -name "firmware.bin" | head -n 1)

          if [ -z "$FILE" ]; then
            echo "Nie znaleziono firmware.bin!"
            exit 1
          fi

          echo "Znaleziono: $FILE"
          mkdir -p output
          cp "$FILE" output/firmware.bin

      - name: Udostępnienie firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output/firmware.bin
